""" Constants & Enums used in other files. """
__author__ = "Jai Wargacki"

SNAKE_UNIT = 10
STARTING_POSITION = (10, 10)
PAUSE_DELAY = 200
FPS = 15

# Directions
NORTH = 0
EAST = 1
SOUTH = 2
WEST = 3

DIMENSION = 60
WINDOW_DIMENSIONS = (DIMENSION * SNAKE_UNIT, DIMENSION * SNAKE_UNIT)
WINDOW_TITLE = "Snake"

MENU_FONT = 'CourierNew'
LARGE_FONT_SIZE = 40
SMALL_FONT_SIZE = 20
START_TEXT = 'Press Space to Start'
SCORE_TEXT = 'Score : %d'
LARGE_TEXT_LOC = (DIMENSION * SNAKE_UNIT / 2, (DIMENSION-10) * SNAKE_UNIT / 2)
SMALL_TEXT_LOC = (DIMENSION * SNAKE_UNIT / 2, DIMENSION * SNAKE_UNIT / 2)

# Colors
SNAKE_COLOR = (0, 230, 0)
BACKGROUND_COLOR = (0, 0, 0)
FOOD_COLOR = (230, 0, 0)
